import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Dashboard from "@/components/dashboard";
import { Providers } from "../providers";

const segoeUIRegular = localFont({
  src: "../fonts/SegoeUI.ttf",
  variable: "--font-segoe-ui",
  weight: "400",
});

const segoeUISemibold = localFont({
  src: "../fonts/seguisb.ttf",
  variable: "--font-segoe-ui-semibold",
  weight: "500",
});

const segoeUIBold = localFont({
  src: "../fonts/SegoeUIBold.ttf",
  variable: "--font-segoe-ui-bold",
  weight: "600, 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <Providers>
        <body
          className={`${segoeUIRegular.variable} ${segoeUIBold.variable} ${segoeUISemibold.variable} antialiased font-segoeUI flex`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
